apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name_prefix }}{{ .Values.workshop_name }}
    class: spawner
    spawner: learning-portal
  name: {{ .Values.name_prefix }}{{ .Values.workshop_name }}-spawner
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8081-tcp
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    deployment: {{ .Values.name_prefix }}{{ .Values.workshop_name }}-spawner
