apiVersion: v1
kind: Route
metadata:
  annotations:
    homeroom/description: {{ .Values.workshop_description }}
    homeroom/group: {{ .Values.homeroom_name }}
    homeroom/title: {{ .Values.workshop_title }}
    kubernetes.io/tls-acme: {{ .Values.lets_encrypt }}
  labels:
    app: {{ .Values.name_prefix }}{{ .Values.workshop_name }}
    class: spawner
    spawner: learning-portal
  name: {{ .Values.name_prefix }}{{ .Values.workshop_name }}-spawner
spec:
  host: {{ .Values.workshop_name }}-{{ .Values.spawner_namespace }}.{{ .Values.cluster_subdomain }}
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.name_prefix }}{{ .Values.workshop_name }}-spawner
    weight: 100
